# Generated by Django 4.1.1 on 2022-10-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=300)),
                ("total_bikes", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("electric_scooters", "electric_scooters"),
                            ("electric_bikes", "electric_bikes"),
                        ],
                        default="electric_scooters",
                        max_length=30,
                    ),
                ),
                ("battery", models.IntegerField(blank=True, default=100, null=True)),
                (
                    "is_defective",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_available",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bike",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.location"
                    ),
                ),
            ],
        ),
    ]
