# Generated by Django 4.1.1 on 2022-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_order_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="total_bikes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
